name: australia_simulator
description: Get the f*ck out of my house.
version: 0.0.1

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  start:   ">=0.2.7 <0.3.0"
  vector_math: any
  rxdart: ^0.15.0
#  path: ^1.4.1

dev_dependencies:
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
