name: australia_simulator
description: Get the f*ck out of my house.
version: 0.0.1

environment:
  sdk: '>=1.24 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
